language: java
jdk: oraclejdk8
sudo: true

branches:
  only:
    - master
cache:
  directories:
  - '$HOME/.m2/repository'

before_script:
  - export JAVA_OPTS="-Xmx2048m"
  - chmod a+x ./mvnw

script:
  - mvn package